# Generated by Django 3.2.9 on 2022-02-08 07:25

from django.db import migrations, models
import django.utils.timezone
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_modified',
            field=notes.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
